language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get upgrade -qq
  - sudo apt-get install libboost-all-dev doxygen gnuplot -qq
before_script:
  - cmake .
script: make clean all test
branches:
  only:
    - master
notifications:
  recipients:
    - home@dreiundzwanzig.biz
  email:
    on_success: change
    on_failure: always
env:
  - RVM=2.0.0
