language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install doxygen
  - sudo apt-get install gnuplot
before_script:
  - cmake .
script: make clean all test
branches:
  only:
    - master
notifications:
  recipients:
    - home@dreiundzwanzig.biz
  email:
    on_success: change
    on_failure: always
env:
  - RVM=2.0.0
