/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef C4Service_CONSTANTS_H
#define C4Service_CONSTANTS_H

#include "C4Service_types.h"

namespace com { namespace cosh { namespace c4 { namespace thrift {

class C4ServiceConstants {
 public:
  C4ServiceConstants();

  std::string VERSION;
};

extern const C4ServiceConstants g_C4Service_constants;

}}}} // namespace

#endif
