/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "C4Service_constants.h"

namespace com { namespace cosh { namespace c4 { namespace thrift {

const C4ServiceConstants g_C4Service_constants;

C4ServiceConstants::C4ServiceConstants() {
  VERSION = "0.0.1";

}

}}}} // namespace

