// Autogenerated by Thrift Compiler (0.9.1)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"C4Service"
	"flag"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  void InsertOrUpdate(TRowKey rowId, TColumnKey columnId, TValue value, TTTL ttl)")
	fmt.Fprintln(os.Stderr, "  TValue Get(TRowKey rowId, TColumnKey columnId)")
	fmt.Fprintln(os.Stderr, "  void TombstoneColumn(TRowKey rowId, TColumnKey columnId)")
	fmt.Fprintln(os.Stderr, "  void TombstoneRow(TRowKey rowId)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = math.MinInt32 // will become unneeded eventually
	_ = strconv.Atoi
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := C4Service.NewC4ClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "InsertOrUpdate":
		if flag.NArg()-1 != 4 {
			fmt.Fprintln(os.Stderr, "InsertOrUpdate requires 4 args")
			flag.Usage()
		}
		argvalue0, err18 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err18 != nil {
			Usage()
			return
		}
		value0 := C4Service.TRowKey(argvalue0)
		tmp1, err19 := (strconv.Atoi(flag.Arg(2)))
		if err19 != nil {
			Usage()
			return
		}
		argvalue1 := byte(tmp1)
		value1 := C4Service.TColumnKey(argvalue1)
		argvalue2 := flag.Arg(3)
		value2 := C4Service.TValue(argvalue2)
		tmp3, err21 := (strconv.Atoi(flag.Arg(4)))
		if err21 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := C4Service.TTTL(argvalue3)
		fmt.Print(client.InsertOrUpdate(value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "Get":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "Get requires 2 args")
			flag.Usage()
		}
		argvalue0, err22 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err22 != nil {
			Usage()
			return
		}
		value0 := C4Service.TRowKey(argvalue0)
		tmp1, err23 := (strconv.Atoi(flag.Arg(2)))
		if err23 != nil {
			Usage()
			return
		}
		argvalue1 := byte(tmp1)
		value1 := C4Service.TColumnKey(argvalue1)
		fmt.Print(client.Get(value0, value1))
		fmt.Print("\n")
		break
	case "TombstoneColumn":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "TombstoneColumn requires 2 args")
			flag.Usage()
		}
		argvalue0, err24 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err24 != nil {
			Usage()
			return
		}
		value0 := C4Service.TRowKey(argvalue0)
		tmp1, err25 := (strconv.Atoi(flag.Arg(2)))
		if err25 != nil {
			Usage()
			return
		}
		argvalue1 := byte(tmp1)
		value1 := C4Service.TColumnKey(argvalue1)
		fmt.Print(client.TombstoneColumn(value0, value1))
		fmt.Print("\n")
		break
	case "TombstoneRow":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "TombstoneRow requires 1 args")
			flag.Usage()
		}
		argvalue0, err26 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err26 != nil {
			Usage()
			return
		}
		value0 := C4Service.TRowKey(argvalue0)
		fmt.Print(client.TombstoneRow(value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
