#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module C4Thrift
  # A specific column was requested that does not exist.
  class NotFoundException < ::Thrift::Exception
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  # Invalid request could mean required parameters are missing, or a parameter is malformed.
# why contains an associated error message.
  class InvalidRequestException < ::Thrift::Exception
    include ::Thrift::Struct, ::Thrift::Struct_Union
    def initialize(message=nil)
      super()
      self.why = message
    end

    def message; why end

    WHY = 1

    FIELDS = {
      WHY => {:type => ::Thrift::Types::STRING, :name => 'why'}
    }

    def struct_fields; FIELDS; end

    def validate
      raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field why is unset!') unless @why
    end

    ::Thrift::Struct.generate_accessors self
  end

end
